apiVersion: v1
kind: Service
metadata:
  labels:
    app: xray
  name: xray-service
spec:
  type: NodePort
  ports:
    - name: tcp-9000
      port: 9000
      targetPort: 9000
      protocol: TCP
      nodePort: $YOUR_NODEPORT
  selector:
    app: xray
